### ISSUE TITLE
🎯[Feat] 프로젝트 구성원 화면 개발

### ISSUE THREAD

**Issue by jlee38266** [OmokNoonE/PPM-frontend#8]
### 기능 요약 (Feature Summary)
프로젝트 구성원 목록을 보여주는 페이지 개발

### 작업 내용 (Work Description)
프로젝트 구성원을 조회 하고 추가/제외 기능이 포함된 화면을 개발

### 체크리스트 (Checklist)
- [x] 새로운 기능에 대한 코드 작성 완료
- [x] 테스트 완료
- [x] 문서화 완료
- [x] 리뷰 요청

**Comment by ms1011** [comment]
화면 재구성
